# Generated by Django 4.2.4 on 2023-08-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapstoneApp', '0002_remove_message_content_message_image_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.URLField(default=' https://my-new-mvp-images.s3.us-west-2.amazonaws.com/pic1.png'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
    ]
